### ISSUE TITLE
Dont Patch Parts that have Module WBIOmniStorage

### ISSUE THREAD

**Issue by TheDogKSP** [post-kerbin-mining-corporation/CryoTanks#114]
The MM patches currently do not patch fuel tanks parts that already define a switcher, such as IFS, firespitter, or WBIConvertableStorage.

This exclusion should also include parts with Module WBIOmniStorage, as these work like WBIConvertibleStorage (just a newer type of storage that Angel-125 is using nowadays).

Example where the CryoTanks patch conflicts with a part that has WBIOmniStorage is in Angel-125's mod MOLE, part wbiShieldedTank.

**Comment by ChrisAdderley** [comment]
Added for 1.6.0 release

**Comment by ChrisAdderley** [comment]
Released fix with 1.6.0.
