### ISSUE TITLE
Stock Methane Tank Options Not Showing

### ISSUE THREAD

**Issue by MagicCards** [post-kerbin-mining-corporation/CryoTanks#116]
I am not getting any options to turn stock tanks into methane tanks. Hydrogen works just fine but not methane. KSP ver 1.10.1 with Near Future, REstock, Kerbalism and Kiwi Tech Tree among other mods installed that shouldn't conflict.

**Comment by ChrisAdderley** [comment]
Need some more info. Chances are you have some other fuel switching mod interfering. 
Log, modlist, etc.

**Comment by MagicCards** [comment]
Full Modlist with Versions

B9 Part Switch (B9PartSwitch v2.17.0)
Better SR Bs (BetterSRBs 1.2.4)
Chatterer (Chatterer 0.9.99)
Community Delta-V Maps (CommunityDeltaVMaps 2:2.8)
Community Resource Pack (CommunityResourcePack 1.4.2)
Community Tech Tree (CommunityTechTree 1:3.4.3)
Community Terrain Texture Pack (CommunityTerrainTexturePack 1:1.0.4)
Contract Configurator (ContractConfigurator 1.30.5)
Cryo Tanks (CryoTanks 1.6.0)
Cryo Tanks Core (CryoTanks-Core 1.6.0)
Cryogenic Engines (CryoEngines 1:2.0.1)
Custom Barn Kit (CustomBarnKit 1.1.21.0)
Deployable Engines Plugin (DeployableEngines 1.3.0)
Dynamic Battery Storage (DynamicBatteryStorage 2:2.2.2.0)
Environmental Visual Enhancements - Stock Planet Config files (EnvironmentalVisualEnhancements-HR 2:EVE-1.2.2-1)
Environmental Visual Enhancements Redux (EnvironmentalVisualEnhancements 3:1.11.2.1)
Hide Empty Tech Tree Nodes (HideEmptyTechNodes 1.2.0)
Kerbal Actuators (KerbalActuators v1.8.3)
Kerbal Alarm Clock (KerbalAlarmClock v3.13.0.0)
Kerbalism (Kerbalism 3.12)
Kerbalism - Default Config (Kerbalism-Config-Default 3.12)
Kiwi Tech Tree Overhaul (KiwiTechTree 1.4.0)
Kopernicus Bleeding Edge Beta - DEV RELEASE (Kopernicus-BE UBEE_1111_80)
Mark IV Spaceplane System (MarkIVSpaceplaneSystem 3.2.0)
MechJeb 2 (MechJeb2 2.11.0.0)
MissingHistory (MissingHistory 1.9)
Mk2 Stockalike Expansion (Mk2Expansion 2:1.8.9.3)
Mk3 Stockalike Expansion (Mk3Expansion 1.5.1)
ModularFlightIntegrator (ModularFlightIntegrator 1.2.7.0)
Module Manager (ModuleManager 4.1.4)
Near Future Aeronautics (NearFutureAeronautics 2.1.0)
Near Future Construction (NearFutureConstruction 1.3.1)
Near Future Electrical (NearFutureElectrical 1.2.1)
Near Future Electrical Core (NearFutureElectrical-Core 1.2.1)
Near Future Exploration (NearFutureExploration 1.1.1)
Near Future IVA Props (NearFutureProps 1:0.6.4)
Near Future Launch Vehicles (NearFutureLaunchVehicles 2.1.3)
Near Future Propulsion (NearFuturePropulsion 1.3.1)
Near Future Solar (NearFutureSolar 1.3.1)
Near Future Solar Core (NearFutureSolar-Core 1.3.1)
Near Future Spacecraft (NearFutureSpacecraft 1.4.1)
Outer Planets Mod (OuterPlanetsMod 2:2.2.9)
PersistentRotation (PersistentRotation 1.8.7)
PlanetShine (PlanetShine 0.2.6.3)
PlanetShine - Default configuration (PlanetShine-Config-Default 0.2.6.3)
Rational Resources (RationalResources 1.14.1)
ReStock (ReStock 1.2.1)
ReStock+ (ReStockPlus 1.2.1)
SCANsat (SCANsat v20.4)
Simple Adjustable Fairings - KW Rocketry Pack (SimpleAdjustableFairings-KWRocketry v1.3.0)
Simple Adjustable Fairings - Plugin (SimpleAdjustableFairings v1.11.0)
Stockalike Station Parts Expansion Redux (StationPartsExpansionRedux 1.4.0)
TriggerAu Flags (TriggerAu-Flags v2.10.0.0)
Waterfall Core (Waterfall 0.6.0)

**Comment by MagicCards** [comment]
[Player.log](https://github.com/post-kerbin-mining-corporation/CryoTanks/files/6113466/Player.log)

**Comment by MagicCards** [comment]
Hope this all helps. To be more clear I can change the cryogenic tanks you provide to methane or hydrogen, just not the stock tanks. They have options like FL/O composite and LH2 among others. No option for methane however, The only other mod I know that allows changing of fuels types that is installed is kerbalism and all its dependencies.

**Comment by ChrisAdderley** [comment]
Some detective work later, determined it's KiwiTechTree. It includes its own version of the CryoTanks universal fuel switcher which has not been updated for the new methalox stuff in CryoTanks yet.

**Comment by MagicCards** [comment]
Ah, thank you. I will inform the author of that mod of the issue then. Thank you so much!
