### ISSUE TITLE
Resource duplication in editor with parts in symmetry 

### ISSUE THREAD

**Issue by coyotesfrontier** [post-kerbin-mining-corporation/CryoTanks#119]
When changing the tank type of a tank in symmetry, all of the other tanks connected in symmetry won't have the original resource removed. The duplicated resource disappears when using certain buttons in the editor (including launch).

Tested on version 1.11.1 with no mods other then CryoTanks and dependencies, also occurs in 1.10.1 and presumably 1.11.2.

Screenshots:
https://imgur.com/a/pOVwANL

**Comment by ChrisAdderley** [comment]
Looks to be an issue with B9PS, I've raised it there. The resources don't seem to be there, it's just the UI not refreshing, so not very urgent to deal with.
