### ISSUE TITLE
Tank Types are not available with SimpleFuelSwitch installed

### ISSUE THREAD

**Issue by PhaserArray** [post-kerbin-mining-corporation/CryoTanks#136]
It seems that having both this and SimpleFuelSwitch by @KSPSnark installed results in the option to change tank types for Stock being hidden/disabled and NF tanks not having the cryo fuels as options. I only noticed because I initially didn't have this mod and used the other mod to hold only liquid fuel for nuclear engines.

I don't think anything needs to be fixed as this mod makes the fuel switcher redundant anyways, but it could be helpful for others to add conflict between the two to the CKAN metadata.

![image](https://user-images.githubusercontent.com/10397412/233875852-9b47cfe7-1c32-43d2-aa14-c275da49e87d.png)

**Comment by ChrisAdderley** [comment]
CKAN metadata now says SimpleFuelSwitch and IFS are incompatible with CT.
