### ISSUE TITLE
Fuel boils off on high timewarp

### ISSUE THREAD

**Issue by Ferristik** [post-kerbin-mining-corporation/CryoTanks#143]
Mods used on the craft:
HeatControl
Sterling Systems Core, Engines and Tankage
NF Electrical
RealChutes
MkIV Expansion

and a zip file of everything you need including a video:
https://www.mediafire.com/file/5d70bqha6r32krj/problem_stuff.zip/file
(couldnt upload directly because github said it was too big)

**Comment by ChrisAdderley** [comment]
This might be related to Better Time Warp... you're running into exactly the problem DBS is supposed to solve but the system is not working.

**Comment by Ferristik** [comment]
> This might be related to Better Time Warp... you're running into exactly the problem DBS is supposed to solve but the system is not working.

i don't use BetterTimeWarp, i use Time Control. does any timewarp mod cause this issue? i've seen other people have this issue too in the r/ksp discord server.

**Comment by ChrisAdderley** [comment]
It's the first I've heard of it. 

There's hints of both mods in the log. 

`[LOG 15:59:35.979] [AddonLoader]: Instantiating addon 'BetterTimeWarp' from assembly 'CameraTools'`

`[LOG 16:16:39.687] [AddonLoader]: Instantiating addon 'TimeControl' from assembly 'CameraTools'`

**Comment by Ferristik** [comment]
very weird, might be a remnant but i don't have bettertimewarp in my gamedata folder

**Comment by Ferristik** [comment]
should i try a reinstall of DBS?

**Comment by ChrisAdderley** [comment]
I installed the stuff to load your ship and a few weird things:

1. Different resource counts when I launched your vessel (note EC in particular). It also looks a little different:
![image](https://github.com/user-attachments/assets/d4b51a48-b68f-4fda-8f8e-0624e6f8df74)

2. The problem does not reproduce (of course). 

I'll install TimeControl later and see if that affects anything, but honestly you have so many mods in your install it will be very hard to track down. 

One thing you could try is opening that Advanced rollout in DBS which shows debug info while the ship is losing power and screenshotting what it says.

**Comment by Ferristik** [comment]
different resource counts are because the original battery was tweakscaled and to reduce the mod count the craft had i rescaled the battery to the original scale.

and yes, i know i have a lot of mods. sorry :(

also how do i open advanced rollout?

**Comment by ChrisAdderley** [comment]
Click the header button that says Advanced

**Comment by Ferristik** [comment]
alright, just gotta wait for KSP to load

**Comment by Ferristik** [comment]
okay i found out the issue. even though im over 100x timewarp, DBS thinks im under 100x. i don't know why
![resim](https://github.com/user-attachments/assets/c0fdfa4d-dd93-4107-ba57-3582d93504a5)

**Comment by ChrisAdderley** [comment]
Yeah that's what I expectedmight be happening. Will look into it.

**Comment by ChrisAdderley** [comment]
Would you be able to repeat your tests? I may have a fix. If you can, grab `DynamicBatteryStorage.dll` from this link: https://github.com/post-kerbin-mining-corporation/DynamicBatteryStorage/tree/dev/GameData/DynamicBatteryStorage/Plugins
and replace the one in your GameData folder with it and let me know the results

**Comment by Ferristik** [comment]
Sorry for late response, i would be very happy to help. i'll post the results soon

**Comment by Ferristik** [comment]
it worked, thank you so much! i finally can go interstellar without problems.

**Comment by ChrisAdderley** [comment]
Sweet, I'll sort out a new release soon.
